variables:
  # CI_DEBUG_TRACE: "true"
  VERSION: $CI_COMMIT_SHORT_SHA

stages:
  - Test
  - Build

Test:
  stage: Test
  image: openjdk:11.0.3-jdk-slim
  script:
    - mvn verify --no-transfer-progress

Build:
  stage: Build
  image: openjdk:11.0.3-jdk-slim
  script:
    - java -version
    #- mvn versions:set -DnewVersion=$VERSION
    - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.wagon.providers.http.httpclient.wire=trace -U -s settings.xml clean deploy -DskipTests=true
