variables:
  # CI_DEBUG_TRACE: "true"
  VERSION: $CI_COMMIT_SHORT_SHA

.only: &only
  only:
    - master
    - /^hotfix.*$/

.only_except_skip_ci: &only_except_skip_ci
  <<: *only
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/i

.only_except_skip_ci_test: &only_except_skip_ci_test
  <<: *only
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/i
      - $CI_COMMIT_MESSAGE =~ /skip-test/i

.only_except_skip_ci_manual: &only_except_skip_ci_manual
  <<: *only_except_skip_ci
  when: manual
  allow_failure: false

stages:
  - Test
  - Build

Test:
  stage: Test
  <<: *only_except_skip_ci_test
  image: maven:3.6.3-jdk-11-slim
  script:
    - mvn verify --no-transfer-progress

Build:
  stage: Build
  <<: *only_except_skip_ci_manual
  image: maven:3.6.3-jdk-11-slim
  script:
    - java -version
    #- mvn versions:set -DnewVersion=$VERSION
    - mvn -U -s settings.xml clean deploy -DskipTests=true
