jdempotent:
  enable: true
  cryptography:
    algorithm: MD5
  cache:
    persistReqRes: false
    couchbase:
      connection-string: XXXXXXXX
      password: XXXXXXXX
      username: XXXXXXXX
      bucket-name: XXXXXXXX
      connect-timeout: 100000
      query-timeout: 20000
      kv-timeout: 3000

email:
  from:
    address: XXXXXXX

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: XXXXXXX
    password: XXXXXXX
    properties.mail.smtp:
      auth: true
      starttls.enable: true

template:
  welcoming:
    subject: "Welcoming"
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"